"""
Merges council/manifestos/*.md into a single draft document.

Deliberately not wired into any runtime import path, self-edit pipeline, or
system prompt — this produces a human-readable aggregation for review, not a
live authority. Nothing in FeralEcho reads council/FERALECHO_CHARTER_DRAFT.md
automatically. If this is ever meant to become a real, consequential document
(e.g. something echo_ground_truth.py surfaces, or something self-edit checks
against), that's a deliberate follow-up decision, not a default of running
this script — same posture as propose_core_edit()'s advisory-only patches and
the Dissent Log's observational-only design.

Run manually: python council/manifesto_sync.py
"""
import json
import os
import re
from datetime import datetime, timezone

_PROJECT_ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
MANIFESTOS_DIR = os.path.join(_PROJECT_ROOT, "council", "manifestos")
OUTPUT_PATH = os.path.join(_PROJECT_ROOT, "council", "FERALECHO_CHARTER_DRAFT.md")

_METADATA_BLOCK_RE = re.compile(r"```json\s*(\{.*?\})\s*```", re.DOTALL)


def _extract_metadata(content: str) -> dict:
    """Pulls the last ```json {...} ``` block in the file (the structural
    metadata section, by this template's convention). Returns {} if none
    found or unparseable — never raises, this is a best-effort read of files
    that may not perfectly match the template."""
    matches = _METADATA_BLOCK_RE.findall(content)
    if not matches:
        return {}
    try:
        return json.loads(matches[-1])
    except (json.JSONDecodeError, ValueError):
        return {}


def load_manifestos() -> list[dict]:
    entries = []
    if not os.path.isdir(MANIFESTOS_DIR):
        return entries
    for filename in sorted(os.listdir(MANIFESTOS_DIR)):
        if not filename.endswith(".md"):
            continue
        path = os.path.join(MANIFESTOS_DIR, filename)
        with open(path, "r", encoding="utf-8") as f:
            content = f.read()
        meta = _extract_metadata(content)
        entries.append({
            "filename": filename,
            "path": path,
            "content": content,
            "metadata": meta,
            "authorship": meta.get("authorship", "unknown"),
        })
    return entries


def build_charter_draft(entries: list[dict]) -> str:
    filled = [e for e in entries if e["authorship"] != "stub_unfilled"]
    stubs = [e for e in entries if e["authorship"] == "stub_unfilled"]

    lines = [
        "# FeralEcho Charter — DRAFT",
        "",
        "**This is a non-authoritative aggregation, not a live document anything reads.**",
        "Generated by `council/manifesto_sync.py` from `council/manifestos/*.md`. "
        "Nothing in FeralEcho's runtime, self-edit pipeline, or system prompts "
        "consults this file automatically — becoming a real, consequential "
        "document is a deliberate future decision, not a default of running "
        "this script.",
        "",
        f"Generated: {datetime.now(timezone.utc).isoformat()}",
        f"Entries: {len(filled)} filled, {len(stubs)} unfilled stub(s)",
        "",
        "---",
        "",
    ]

    for e in filled:
        meta = e["metadata"]
        lines.append(f"## {meta.get('entity_name', e['filename'])}")
        lines.append("")
        lines.append(
            f"*authorship: `{e['authorship']}` | "
            f"integration_status: `{meta.get('integration_status', 'unknown')}` | "
            f"vetoes: {meta.get('vetoes', [])}*"
        )
        lines.append("")
        lines.append(e["content"].strip())
        lines.append("")
        lines.append("---")
        lines.append("")

    if stubs:
        lines.append("## Unfilled stubs (not yet part of the draft)")
        lines.append("")
        for e in stubs:
            lines.append(f"- {e['metadata'].get('entity_name', e['filename'])} (`{e['filename']}`)")
        lines.append("")

    return "\n".join(lines)


def main():
    entries = load_manifestos()
    draft = build_charter_draft(entries)
    with open(OUTPUT_PATH, "w", encoding="utf-8") as f:
        f.write(draft)
    filled = sum(1 for e in entries if e["authorship"] != "stub_unfilled")
    print(f"[manifesto_sync] Wrote {OUTPUT_PATH} — {filled}/{len(entries)} entries filled.")


if __name__ == "__main__":
    main()
